sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="mopidy"
  - ADDON="test"
  - ADDON="device-list"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON 
